#!/bin/bash
if [[ $(pwd) = */scripts ]]; then
 cd ..
fi
if [[ $# -eq 0 ]];then
  kcenv="LOCAL"
  kctag="latest"
else
  kcenv=$1
  kctag=$2
fi
. ./scripts/setenv.sh

echo "Deploy helm chart for $chart project to $ns"


verifyPod(){
  kubectl logs $1 -n $ns
}

echo "############################"
oq=$(helm list | grep $kname | awk '{print $1}')
if [[ -z "$oq" ]]
then
  echo "$kname release not deployed..."
  cd ./chart
  if [[ "$kcenv" == "MINIKUBE" ]]
  then
    helm install $chart/ --name $kname --set image.repository=ibmcase/kc-ui --set image.tag=$kctag --set image.pullSecret= --set image.pullPolicy=Never --set eventstreams.brokers=kafkabitmani:9092 --set eventstreams.env=MINIKUBE --namespace $ns
  else
    helm install $chart/ --name $kname --namespace $ns 
  fi
  sleep 4
else
    echo "$kname release deployed, here is the pod logs"
    helm upgrade $msname $chart/
    helm history $msname
fi
podId=$(kubectl get pods -n $ns | grep $msname | awk '{print $1}')
verifyPod $podId
