name: Build & push image for 'kc-ui'
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'chart/**'
      - 'docs/**'

jobs:
  build-docker-image:
    #if: startsWith(github.repository, 'ibm-cloud-architecture/')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Validate DOCKER_USERNAME is defined
      id: validate-docker-username
      run: |
        [ -z "${VALUE}" ] && { echo "The secret ${FIELD} needs to be set on this repository."; exit 1; }
      env:
        FIELD: DOCKER_USERNAME
        VALUE: ${{ secrets.DOCKER_USERNAME }}
    - name: Bump version and push tag
      id: bump-version-action
      uses: anothrNick/github-tag-action@master
      env:
        DEFAULT_BUMP: patch
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the ui docker image
      id: build-ui-image
      run: |
        IMAGE_NAME="${DOCKER_R}/${DOCKER_I}"
        docker login -u ${DOCKER_U} -p ${DOCKER_P}
        cd ${WORKDIR}
        docker build . --file ${DOCKERFILE} --tag ${IMAGE_NAME}:${IMAGE_TAG}
        docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${IMAGE_NAME}:latest
        docker push ${IMAGE_NAME}
      env:
        DOCKER_U: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_P: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_R: ${{ secrets.DOCKER_REPOSITORY }}
        DOCKER_I: ${{ secrets.DOCKER_IMAGE }}
        WORKDIR: .
        DOCKERFILE: Dockerfile
        #IMAGE_NAME: ibmcase/kcontainer-ui
        IMAGE_TAG: ${{ steps.bump-version-action.outputs.new_tag }}
    - name: Webhook to GitOps repo
      id: gitops-repo-webhook
      uses: osowski/repository-dispatch@v1
      with:
        token: ${{ secrets.WEBHOOK_TOKEN }}
        repository: ibm-cloud-architecture/refarch-kc-gitops
        event-type: gitops-refresh
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "source": "${{ github.repository }}"}'
